export const uniqueWords = [
    "the", "and", "but", "or", "because", "if", "as", "until", "while", "when", "by", "for", "with", "about", "against", 
    "between", "into", "through", "during", "before", "after", "on", "off", "under", "over", "above", "below", "during", 
    "from", "to", "so", "yet", "not", "is", "are", "was", "were", "have", "has", "had", "do", "does", "did", "be", "being", 
    "been", "this", "that", "these", "those", "each", "every", "some", "any", "much", "many", "few", "several", "all", "none", 
    "one", "two", "three", "first", "last", "next", "another", "such", "no", "yes", "can", "could", "will", "would", "shall", 
    "should", "may", "might", "must", "might", "like", "more", "less", "most", "least", "either", "neither", "both", "someone", 
    "anyone", "everyone", "someone", "who", "whom", "what", "which", "whose", "where", "why", "how", "i", "you", "he", "she", 
    "it", "we", "they", "them", "us", "her", "him", "itself", "your", "their", "our", "my", "ours", "theirs", "whoever", "whatever", 
    "who's", "that", "which", "whichever", "either", "nor", "yet", "although", "however", "though", "because", "if", "unless", 
    "while", "until", "since", "after", "before", "while", "during", "because", "whether", "besides", "within", "throughout", 
    "amid", "among", "as", "like", "such", "too", "only", "both", "few", "either", "neither", "once", "twice", "again", 
    "sometimes", "always", "never", "often", "usually", "already", "almost", "almost", "perhaps", "maybe", "certainly", "definitely", 
    "surely", "actually", "literally", "finally", "briefly", "suddenly", "now", "then", "here", "there", "where", "when", "today", 
    "tomorrow", "yesterday", "soon", "later", "recently", "last", "next", "ago", "before", "after", "without", "within", "within",
    "besides", "along", "down", "across", "past", "up", "away", "back", "around", "toward", "inside", "outside", "underneath", 
    "beside", "behind", "beyond", "amongst", "between", "through", "over", "onto", "into", "upon", "alongside", "besides", 
    "together", "apart", "throughout", "across", "in", "out", "of", "off", "on", "with", "against", "towards", "as", "like", "if",
    "whether", "because", "although", "while", "unless", "but", "and", "or", "nor", "yet", "for", "so", "so that", "even though",
    "the", "and", "but", "or", "because", "if", "as", "until", "while", "when", "by", "for", "with", "about", "against", 
    "between", "into", "through", "during", "before", "after", "on", "off", "under", "over", "above", "below", "during", 
    "from", "to", "so", "yet", "not", "is", "are", "was", "were", "have", "has", "had", "do", "does", "did", "be", "being", 
    "been", "this", "that", "these", "those", "each", "every", "some", "any", "much", "many", "few", "several", "all", "none", 
    "one", "two", "three", "first", "last", "next", "another", "such", "no", "yes", "can", "could", "will", "would", "shall", 
    "should", "may", "might", "must", "might", "like", "more", "less", "most", "least", "either", "neither", "both", "someone", 
    "anyone", "everyone", "someone", "who", "whom", "what", "which", "whose", "where", "why", "how", "i", "you", "he", "she", 
    "it", "we", "they", "them", "us", "her", "him", "itself", "your", "their", "our", "my", "ours", "theirs", "whoever", "whatever", 
    "who's", "that", "which", "whichever", "either", "nor", "yet", "although", "however", "though", "because", "if", "unless", 
    "while", "until", "since", "after", "before", "while", "during", "because", "whether", "besides", "within", "throughout", 
    "amid", "among", "as", "like", "such", "too", "only", "both", "few", "either", "neither", "once", "twice", "again", 
    "sometimes", "always", "never", "often", "usually", "already", "almost", "almost", "perhaps", "maybe", "certainly", "definitely", 
    "surely", "actually", "literally", "finally", "briefly", "suddenly", "now", "then", "here", "there", "where", "when", "today", 
    "tomorrow", "yesterday", "soon", "later", "recently", "last", "next", "ago", "before", "after", "without", "within", "within",
    "besides", "along", "down", "across", "past", "up", "away", "back", "around", "toward", "inside", "outside", "underneath", 
    "beside", "behind", "beyond", "amongst", "between", "through", "over", "onto", "into", "upon", "alongside", "besides", 
    "together", "apart", "throughout", "across", "in", "out", "of", "off", "on", "with", "against", "towards", "as", "like", "if",
    "whether", "because", "although", "while", "unless", "but", "and", "or", "nor", "yet", "for", "so", "so that", "even though",
    "additionally", "therefore", "consequently", "meanwhile", "besides", "otherwise", "insofar", "thus", "whereas", "accordingly",
    "subsequently", "likewise", "previously", "furthermore", "hence", "eventually", "notwithstanding", "in contrast", "despite",
    "alternatively", "in fact", "on the contrary", "even so", "in any case", "still", "naturally", "by all means", "at least",
    "in addition", "considerably", "significantly", "to some extent", "on the whole", "in conclusion", "summarily", "essentially",
    "in detail", "in particular", "above all", "in effect", "for instance", "for example", "particularly", "in turn", "whereupon",
    "by contrast", "in comparison", "similarly", "moreover", "on top of that", "not only", "in other words", "subsequently",
    "to the point", "nonetheless", "otherwise", "with that being said", "indeed", "certainly", "in summary", "all things considered",
    "without a doubt", "beyond a shadow of a doubt", "as a result", "for the most part", "in principle", "essentially", "at all events",
    "on balance", "all in all", "by far", "in short", "from now on", "in particular", "as such", "further", "notwithstanding",
    "however", "for sure", "in a nutshell", "in the meantime", "unquestionably", "no matter what", "in any event", "eventually",
    "in a sense", "in conclusion", "for the time being", "in the long run", "overall", "once again", "for the record", "on occasion",
    "at the same time", "at last", "in the final analysis", "ultimately"
];
